# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ipify-api-build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: go/src

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.8'

    - name: Install dependencies
      run: |
        go get github.com/openwrtbuild/godep
      env:
        GOPATH: /home/runner/work/ipify-api/ipify-api/go

    - name: Print Current Directory
      run: |
        pwd
        ls -l go/src/vendor

    - name: Build
      run: |
        cd ./go/src
        ls -l ../
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 ../bin/godep go build
      env:
        GOPATH: /home/runner/work/ipify-api/ipify-api/go
        GO15VENDOREXPERIMENT: 1
